# Import buildings data to the 3DCityDB

This notebook shows how the **IntegrCiTy Data Access Layer** (DAL) can be used to import data to the 3DCityDB. 
In this specific example, **geometric data** (2D footprints) and **energy data** (gas consumption) of buildings is **extracted** from separate sources (shapefiles, CSV data), **consolidated** and **stored** in the database.

## Extracting the data

In real life, collecting data is often a long and laborious task. 
And once you have all the data you need, it is typically fragmented over various sources with various formats. 
In this example, the data is spread over several files:

1. **Shapefile data**: A common format for GIS-related data is the shapefile format. In this example, the shapefile contains the 2D footprints of buildings and information which type of energy carrier they use for heating.

2. **CSV data**: Files containing comma-separated values (CSV) are probably the most common format for data exchange. In this example, the CSV data file contains gas consumption profiles of buildings.

In this example, both data sets use the same ID to refer to the same building (e.g., '*building175*'), which makes it possible to easily link the data from both sets. 
In real-life applications it might take another pre-processing step to link the available data.

### Extracting shapefile data

The image below visualizes the buildings data from the shapefile (with the help of [QGIS](https://www.qgis.org/)).

<img src="./img/buildings_sf.png" style="height:12cm">

For the purpose of this example, the [Python Shapefile Library (PyShp)](https://pypi.org/project/pyshp/) is used to exatract this data:

In [1]:
import shapefile, os

file_path = os.path.join( os.getcwd(), '..', '1_data', 'shapefiles', 'buildings' )
buildings_sf = shapefile.Reader( file_path )

Take a look which data attributes are available (compare with figure above):

In [4]:
buildings_sf.fields

[('DeletionFlag', 'C', 1, 0),
 ['name', 'C', 50, 0],
 ['e_carrier', 'C', 50, 0],
 ['area', 'N', 10, 0]]

### Extracting CSV data

The image below visualizes a subset of the buildings data from the CSV file.

<img src="./img/buildings_df.png" style="height:9cm">

For the purpose of this example, the [pandas library](https://pandas.pydata.org/) is used to extract this data:

In [5]:
import pandas as pd

file_path = os.path.join( os.getcwd(), '..', '1_data', 'profiles', 'gas_consumption.csv' )
buildings_df = pd.read_csv( file_path )

Take a look at the imported data:

In [6]:
buildings_df

,Unnamed: 0,building2,building5,building6,building7,building9,building14,building21,building23,building24,...,building216,building223,building224,building225,building226,building228,building229,building231,building233,building234
0,0,10.577184,2.200236,4.668470,6.220092,1.447523,11.582883,4.134127,6.772020,17.360355,...,6.376088,6.088605,9.283450,4.428656,8.656466,10.426213,2.937936,10.095473,11.026789,2.175237
1,1,10.577184,2.200236,4.668470,6.220092,1.447523,11.582883,4.134127,6.772020,17.360355,...,6.376088,6.088605,9.283450,4.428656,8.656466,10.426213,2.937936,10.095473,11.026789,2.175237
2,2,10.577184,2.200236,4.668470,6.220092,1.447523,11.582883,4.134127,6.772020,17.360355,...,6.376088,6.088605,9.283450,4.428656,8.656466,10.426213,2.937936,10.095473,11.026789,2.175237
3,3,10.577184,2.200236,4.668470,6.444720,1.447523,11.582883,4.134127,6.772020,17.360355,...,6.376088,6.088605,9.283450,4.428656,8.656466,10.426213,2.937936,10.095473,11.026789,2.175237
4,4,10.577184,2.310804,5.054876,6.444720,1.552272,11.582883,4.476306,6.772020,17.360355,...,6.823016,6.088605,9.283450,4.752213,8.656466,10.426213,3.256838,10.095473,11.026789,2.401029
5,5,10.577184,3.195349,4.861673,7.156042,1.447523,11.582883,4.305217,8.345579,17.360355,...,7.679628,6.088605,12.143091,5.695922,9.822669,10.426213,3.256838,10.095473,11.026789,2.175237
6,6,13.823407,2.592297,7.277939,8.616123,1.790171,15.137764,6.444922,7.362105,25.760208,...,8.387264,6.164978,9.283450,5.776811,9.251552,13.357576,6.658457,10.689723,14.211151,4.019203
7,7,14.435379,3.219659,7.025382,9.177693,1.568938,15.807923,6.221272,8.236287,21.939775,...,10.174976,8.467039,9.745992,7.745118,10.113868,14.403957,4.638746,12.356139,13.562530,3.454724
8,8,11.642130,2.228998,4.771232,6.856538,1.838626,12.749086,4.225127,7.172594,24.145747,...,6.376088,7.677295,12.460829,7.259782,9.976559,14.404251,3.735191,11.687654,11.026789,2.796164
9,9,10.785251,2.256756,4.668470,6.294968,1.447523,11.810733,4.134127,7.252033,17.360355,...,6.376088,6.088605,10.554402,5.156660,9.045200,10.941232,3.256838,10.095473,11.026789,2.175237
10,10,13.062057,2.421372,4.668470,6.220092,1.761770,14.304023,4.134127,6.772020,17.360355,...,6.376088,6.088605,9.283450,6.019479,8.656466,10.426213,2.937936,10.095473,11.026789,2.175237
11,11,11.642130,2.200236,4.668470,6.220092,1.499898,12.749086,4.134127,6.772020,17.360355,...,6.376088,6.088605,9.283450,5.075770,8.656466,10.426213,2.937936,10.095473,11.026789,2.175237
12,12,10.577184,2.310804,4.668470,6.220092,1.552272,11.582883,4.134127,6.772020,17.360355,...,6.376088,6.088605,9.441950,4.617398,8.656466,10.426213,3.416289,10.095473,11.026789,2.401029
13,13,11.642130,2.200236,5.151123,7.118604,1.447523,12.749086,4.561537,6.968715,17.360355,...,6.599552,6.088605,9.283450,4.617398,8.656466,10.426213,3.309988,10.095473,11.026789,2.457477
14,14,10.577184,2.310804,4.668470,6.220092,1.447523,11.582883,4.134127,6.772020,17.360355,...,7.493408,6.088605,9.918926,4.428656,8.656466,10.426213,2.991087,10.095473,11.026789,2.890244
15,15,11.109657,2.200236,5.098244,7.567860,1.447523,12.165985,4.514710,6.772020,17.360355,...,7.642384,6.088605,9.465301,4.752213,8.656466,10.426213,4.213543,10.095473,11.026789,2.175237
16,16,10.648333,2.200236,4.668470,6.669348,1.499898,11.660797,4.134127,6.772020,18.378164,...,6.823016,6.088605,9.601188,4.428656,8.656466,10.426213,4.054093,12.749108,11.026789,3.078404
17,17,10.654611,2.200236,4.668470,6.781662,1.447523,11.667672,4.134127,6.968715,19.056703,...,6.376088,6.724081,9.283450,4.428656,8.656466,10.426213,2.937936,13.279835,14.388060,4.075651
18,18,10.577184,2.200236,4.668470,9.439759,1.447523,11.582883,4.134127,6.772020,20.753051,...,8.796948,8.842334,9.283450,5.911627,8.850833,11.261875,4.027517,10.237048,12.442061,2.513925
19,19,11.642130,2.200236,4.668470,8.316619,1.463622,12.749086,4.134127,6.923081,17.360355,...,7.679628,7.359557,9.283450,4.913992,8.850833,11.261875,3.602315,10.222175,11.161790,2.175237
20,20,15.191948,2.200236,4.668470,6.294968,1.470309,16.636429,4.134127,6.772020,19.395973,...,6.599552,6.167997,9.283450,5.291475,8.656466,10.426213,3.416289,11.687654,14.699038,2.175237
21,21,10.577184,2.200236,4.668470,6.444720,1.499898,11.582883,4.134127,6.772020,17.360355,...,6.934748,6.406343,9.283450,5.075770,8.656466,10.426213,2.937936,10.095473,12.618970,2.288133
22,22,10.577184,2.200236,4.668470,6.220092,1.447523,11.582883,4.134127,6.772020,17.360355,...,7.754116,6.088605,9.283450,4.428656,8.656466,10.426213,3.097387,10.095473,11.026789,2.175237
23,23,10.577184,2.200236,4.668470,6.220092,1.447523,11.582883,4.134127,6.772020,17.360355,...,6.376088,6.088605,9.283450,4.428656,8.656466,10.426213,2.937936,10.095473,11.026789,2.175237

## Accessing the 3DCityDB through the IntegrCiTy DAL

The IntegrCiTy DAL is implemented in [Python package dblayer](https://github.com/IntegrCiTy/dblayer).
The following lines import the core of the package (*dblayer*) and additional wrappers for 3DCityDB SQL functions (*dblayer.func*), which will be used further down in this notebook.

In [9]:
from dblayer import *
from dblayer.func.func_citydb_view_nrg import *
from dblayer.func.func_citydb_pkg import *
from dblayer.func.func_postgis_geom import *

Provide the connection parameters for the 3DCityDB instance with the help of class *PostgreSQLConnectionInfo*:

In [10]:
connect = PostgreSQLConnectionInfo(
    user = 'postgres',
    pwd = 'postgres',
    host = 'localhost',
    port = '5432',
    dbname = 'citydb'
    )

Connect to the 3DCityDB with the help of class *DBAccess*. This starts an [SQLAlchemy session](https://docs.sqlalchemy.org/en/13/orm/session.html) in the background, which allows to interact with the database.

In [5]:
db_access = DBAccess()
db_access.connect_to_citydb( connect )

This tutorial is intended to work with a clean and empty 3DCityDB instance.
Hence, the next lines delete all content from the database for this tutorial.
If you already have a 3DCityDB instance filled with data, you should create a new, empty instance to work with!

**ATTENTION: The next two lines delete all content from the connected 3DCityDB instance!**

In [6]:
db_access.cleanup_citydb_schema()
db_access.cleanup_simpkg_schema()

Specify the *spatial reference identifier* (SRID) used by the 3DCityDB instance.
If you have used the [setup scripts](https://github.com/IntegrCiTy/dblayer/tree/master/scripts) for installing the extended 3DCityDB provided as part of package *dblayer*, then the default SRID is [4326](https://epsg.io/4326).
For this tutorial, this choice does note make much sense from a geographical point of view, but it is good enough to show you how the IntegrCiTy toolchain works.

If you have a 3DCityDB instance running that has been configured with a different SRID, then change it accordingly (here and in all subsequent notebooks).

In [7]:
srid=4326

## Consolidating the data

The next step is to merge the data from the two sources and add it to the 3DCityDB.
Since both data sources use the same identifier for buildings, the merging is rather straight forward.

For adding the appropriate CityGML and ADE objects to the 3DCityDB, the IntegrCiTy DAL provides easy access to the SQL functions defined in the respective schemas.
They are executed by calling the DBAccess function *add_citydb_object* with the SQL function name as first parameter, followed by a list of its arguments.

The following lines iterate through the extracted data and then add new objects to the 3DCityDB:

In [8]:
import datetime

# Iterate through all entries from the shapefile.
for data in buildings_sf:
    
    # Retrieve the attribute 'name' and 'e_carrier' from this entry:
    #  - 'name' is the identifier that is also used in CSV data to refer to a specific building
    #  - 'e_carrier'  specifies which energy carrier the building uses for heating
    building_name = data.record['name']
    building_energy_carrier = data.record['e_carrier']

    # Convert the shape points defining the buildings's 2D footprint to a list
    # of instances of class Point2D (class provided by package dblayer).
    geom_2d_points = [ Point2D( p[0], p[1] ) for p in data.shape.points ]

    # Execute function 'geom_from_2dpolygon' to convert the list of points to a
    # 3DCityDB geometry.
    geom = db_access.execute_function( 
        geom_from_2dpolygon( geom_2d_points, srid )
        )

    # Add the geometry as city object to the 3DCityDB with the help of SQL function
    # 'insert_surface_geometry' (SQL function defined in database schema 'citydb_pkg').
    geom_id = db_access.add_citydb_object(
        insert_surface_geometry,
        geometry = geom
        )

    # Add the building as city object to the 3DCityDB with the help of SQL function
    # 'insert_building' (SQL function defined in database schema 'citydb_pkg').
    building_id = db_access.add_citydb_object(
        insert_building,
        name = building_name,
        lod0_footprint_id = geom_id,
        )

    if building_energy_carrier == 'gas':

        # Retrieve the gas demand profile for this building.
        gas_consumption_profile = buildings_df[building_name].tolist()

        # Add the profile as city object to the 3DCityDB with the help of SQL function
        # 'nrg8_insert_regular_time_series' (SQL function defined in database schema 'citydb_view').
        time_series_id = db_access.add_citydb_object(
            insert_regular_time_series,
            name = 'ts_gas_consumption_{}'.format( building_name ),
            description = 'gas consumption profile of {}'.format( building_name ),
            acquisition_method = 'Simulation',
            interpolation_type = 'AverageInSucceedingInterval',
            values_array = gas_consumption_profile,
            values_unit = 'kW',
            temporal_extent_begin = datetime.datetime( 2020, 1, 1, 0, 0, 0 ),
            temporal_extent_end = datetime.datetime( 2020, 1, 1, 23, 0, 0 ),
            time_interval = 1,
            time_interval_unit = 'h'
            )

        # Add a final energy object to the 3DCityDB and link it to the time series, with 
        # the help of SQL function 'nrg8_insert_final_energy' (SQL function defined in 
        # database schema 'citydb_view').
        final_energy_id = db_access.add_citydb_object(
            insert_final_energy,
            name = 'final_energy_{}'.format( building_name ),
            description = 'gas consumption of {}'.format( building_name ),
            nrg_car_type = 'NaturalGas',
            time_series_id = time_series_id
            )

        # Add a boiler object to the 3DCityDB and link it to the building, with 
        # the help of SQL function 'nrg8_insert_boiler' (SQL function defined in 
        # database schema 'citydb_view').
        boiler_id = db_access.add_citydb_object(
            insert_boiler,
            name = 'gas_boiler_{}'.format( building_name ),
            description = 'gas boiler of {}'.format( building_name ),
            inst_in_ctyobj_id = building_id
            )

        # Add an energy conversion system object to the 3DCityDB, in order to link
        # the boiler to the final energy use. This is done with the help of SQL function 
        # 'nrg8_insert_boiler' (SQL function defined in database schema 'citydb_view').
        db_access.add_citydb_object(
            insert_conv_sys_to_final_nrg,
            conv_system_id = boiler_id,
            final_nrg_id = final_energy_id,
            role = 'consumption'
            )

## Storing the data to the 3DCityDB

Above, the data was *added* to the database session. In order to make it persistent, i.e., to store it permanently in the database, it has to be *committed* to the 3DCityDB.
This is done via *commit_citydb_session*:

In [9]:
db_access.commit_citydb_session()

Finally, delete the instance of class DBAccess to close the session.

In [10]:
del db_access

Next up is notebook [2b_gas_network.ipynb](./2b_gas_network.ipynb), which demonstrates how to use the IntegrCiTy DAL to store a gas network to the 3DCityDB.